[package]
name = "hyprconfig"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
dirs = "6.0.0"
gpui = "0.2.2"
gpui-component = "0.3.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
